
workspace(name = "aperturedb")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz"],
  strip_prefix = "googletest-1.13.0"
)
